# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}
- {name: 'Posts', path: 'menu', url: 'posts.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'fab fa-discord', link: 'https://discord.com/invite/RXrkd8'}
- {icon: 'fab fa-github', link: 'https://github.com/epsimatt'}
- {icon: 'fas fa-envelope', link: 'mailto:epsimatt@protonmail.com'}

# Customize site text
pagination:
  next_page: '>'
  previous_page: '<'

sharing_button_prompt: ''

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
